channels:
  - conda-forge
dependencies:
  - r-base=3.6
  - r-tidyverse
  - r-terra
  - r-tmap
  - r-raster
  - r-sf
  - r-viridis
  - r-rgdal
  - r-tidyverse
  - r-tidyr
  - r-plyr
  - r-gifski
  - r-curl